/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
    FunctionalTestSidebar: [
        {
            type: 'autogenerated',
            dirName: 'functional_test',
            //label: '功能测试',
        },
    ],
    PerformanceTestSidebar: [
        {
            type: 'autogenerated',
            dirName: 'performance_test',
            //label: '性能测试',
        },
    ],
    AutomatedtestSidebar: [
        {
            type: 'autogenerated',
            dirName: 'automated_test',
            //label: '自动化测试',
        },
    ],
    SecurityTestSidebar: [
        {
            type: 'autogenerated',
            dirName: 'security_test',
            //label: '安全测试',
        },
    ],
    OperationsSidebar: [
        {
            type: 'autogenerated',
            dirName: 'operations',
            //label: '运维',
        },
    ],
    DevLanguageSidebar: [
        {
            type: 'autogenerated',
            dirName: 'development_language',
            //label: '开发语言',        
        },
    ],
    DatabaseSidebar: [
        {
            type: 'autogenerated',
            dirName: 'database',
            //label: '数据库',
        },
    ],
    DevelopSidebar: [
        {
            type: 'autogenerated',
            dirName: 'develop',
            //label: '开发实现',
            //items: [],
        },
    ],
    TestToolSidebar: [
        {
            type: 'autogenerated',
            dirName: 'test_tool',
            //label: '测试工具',
            //items: [],
        },
    ],
};

module.exports = sidebars;
